### ISSUE TITLE
请问报错FileNotFoundError: [Errno 2] No such file or directory: 'config/iLog.log'如何处理，谢谢

### ISSUE THREAD

**Issue by 19819068211** [cyear/ice-study#1]
Traceback (most recent call last):
  File "C:\Users\jl\ice-study\main.py", line 9, in <module>
    main()
  File "C:\Users\jl\ice-study\main.py", line 5, in main
    ice = ice_study()
  File "C:\Users\jl\ice-study\core\ice.py", line 33, in __init__
    self.iLog(res, 0)
  File "C:\Users\jl\ice-study\core\crates\Log.py", line 45, in log
    self._file(text, model)
  File "C:\Users\jl\ice-study\core\crates\Log.py", line 69, in _file
    with open(self.file, "a+") as a:
FileNotFoundError: [Errno 2] No such file or directory: 'config/iLog.log'

**Comment by cyear** [comment]
> Traceback (most recent call last):
>   File "C:\Users\jl\ice-study\main.py", line 9, in <module>
>     main()
>   File "C:\Users\jl\ice-study\main.py", line 5, in main
>     ice = ice_study()
>   File "C:\Users\jl\ice-study\core\ice.py", line 33, in __init__
>     self.iLog(res, 0)
>   File "C:\Users\jl\ice-study\core\crates\Log.py", line 45, in log
>     self._file(text, model)
>   File "C:\Users\jl\ice-study\core\crates\Log.py", line 69, in _file
>     with open(self.file, "a+") as a:
> FileNotFoundError: [Errno 2] No such file or directory: 'config/iLog.log'

由于目前还未收工，暂时未经过windows适配，我在linux上开发的

**Comment by cyear** [comment]
> Traceback (most recent call last):
>   File "C:\Users\jl\ice-study\main.py", line 9, in <module>
>     main()
>   File "C:\Users\jl\ice-study\main.py", line 5, in main
>     ice = ice_study()
>   File "C:\Users\jl\ice-study\core\ice.py", line 33, in __init__
>     self.iLog(res, 0)
>   File "C:\Users\jl\ice-study\core\crates\Log.py", line 45, in log
>     self._file(text, model)
>   File "C:\Users\jl\ice-study\core\crates\Log.py", line 69, in _file
>     with open(self.file, "a+") as a:
> FileNotFoundError: [Errno 2] No such file or directory: 'config/iLog.log'

等待完善之后会使用windows测试的
